// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.DataAccess.Context;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20220208000121_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("TodoApp.DataAccess.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("457bedde-eddd-493f-b92e-7f29d6cefad6"),
                            Created = new DateTime(2022, 2, 7, 17, 1, 21, 513, DateTimeKind.Local).AddTicks(8143),
                            Description = "The First Description",
                            Finished = true,
                            Title = "First Todo Item",
                            Updated = new DateTime(2022, 2, 7, 17, 1, 21, 513, DateTimeKind.Local).AddTicks(8179)
                        },
                        new
                        {
                            Id = new Guid("00a87186-4c77-4402-82c6-8136b4b954bd"),
                            Created = new DateTime(2022, 2, 7, 17, 1, 21, 513, DateTimeKind.Local).AddTicks(8218),
                            Description = "The Second Description",
                            Finished = false,
                            Title = "Second Todo Item",
                            Updated = new DateTime(2022, 2, 7, 17, 1, 21, 513, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            Id = new Guid("2a329d6a-876c-4027-8df8-7c4521839368"),
                            Created = new DateTime(2022, 2, 7, 4, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make a Todo app for Tonic",
                            Finished = false,
                            Title = "Code Interview",
                            Updated = new DateTime(2022, 2, 7, 4, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
